[snowflake]
account = "{{ cookiecutter.snowflake_account }}"
user = "{{ cookiecutter.snowflake_user }}"
role = "role"
warehouse = "{{ cookiecutter.warehouse_name }}"
database = "{{ cookiecutter.database }}"
schema = "{{ cookiecutter.schema }}"
private_key_file = "/path/to/private_key.pem"
private_key_file_pwd = "passphrase"
# Leave query_tag = 'streamtlit' and add any other tags you want to use
session_parameters.query_tag = "streamlit"